### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by cyberic99** [jberg/milkdrop-editor-electron#1]
When doing 'npm install', I get this error message:

```
...
Binary found at /home/eric/tmp/milkdrop-editor-electron/node_modules/node-sass/vendor/linux-x64-59/binding.node
Testing binary
Binary is fine

> milkdrop-editor-electron@0.0.2 postinstall /home/eric/tmp/milkdrop-editor-electron
> node -r babel-register internals/scripts/CheckNativeDep.js && npm run build-dll && electron-builder install-app-deps


> milkdrop-editor-electron@0.0.2 build-dll /home/eric/tmp/milkdrop-editor-electron
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors

/home/eric/tmp/milkdrop-editor-electron/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/eric/tmp/milkdrop-editor-electron/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/eric/tmp/milkdrop-editor-electron/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/eric/tmp/milkdrop-editor-electron/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/eric/tmp/milkdrop-editor-electron/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! milkdrop-editor-electron@0.0.2 build-dll: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the milkdrop-editor-electron@0.0.2 build-dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eric/.npm/_logs/2020-02-24T09_43_59_560Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! milkdrop-editor-electron@0.0.2 postinstall: `node -r babel-register internals/scripts/CheckNativeDep.js && npm run build-dll && electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the milkdrop-editor-electron@0.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eric/.npm/_logs/2020-02-24T09_43_59_841Z-debug.log
```

[2020-02-24T09_43_59_841Z-debug.log](https://github.com/jberg/milkdrop-editor-electron/files/4243887/2020-02-24T09_43_59_841Z-debug.log)

**Comment by jberg** [comment]
Hi, yea, this is unfortunately very unfinished. I will update the README to say as much. Sorry about that

**Comment by cyberic99** [comment]
ok @jberg no problem, it seemed to be a cool app, judging by its name, so I decided to try it...

Is there any usable milkdrop preset editor you would know?

**Comment by jberg** [comment]
As far as I know, the only one is the builtin one available in Winamp
